# Generated by Django 5.2.7 on 2025-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('doctor_assigned', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('room_number', models.IntegerField()),
            ],
        ),
    ]
