# Generated by Django 5.2.7 on 2025-11-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_patient_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doc_image',
            new_name='patient_image',
        ),
    ]
